---
title: "Spectra_Processing"
author: "Simon Oiry"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r Library}
library(tidyverse)
library(Utilities.Package)
library(terra)
library(tidyterra)
```

```{r data opening}

df <-  read_table("Data/CSV/all_spectra.csv")

df_long <- df %>% 
  pivot_longer(-Wavelength, names_to = "Name",values_to = "ref") %>% 
  mutate(Name = gsub(".asd","",Name),
         Spectra = as.numeric(gsub("\\D", "", Name)),
         dataset_Name = gsub("[[:digit:]]","",Name),
         dataset_Name = gsub("GRA-","",dataset_Name))

```

```{r loop across notebooks}

notebooks <- list.files("./Data/Notebook", full.names = T) %>% 
  as.data.frame() %>% 
  rename(path = ".") %>% 
  mutate(name = gsub(".*/","",path),
         site = gsub(".*_","",name) %>% gsub(".txt","",.))

for(i in 1:nrow(notebooks)){
  
  nb <- read.delim(notebooks$path[i])%>% 
      dplyr::filter(Obs == "Gracilaria")
  print(unique(nb$Site))
  
  if(unique(nb$Site) %in% c("BEL","MORB")){
    nb <- nb %>% 
      mutate(Start = Start+100000,
             End = End+100000)
  }else if(unique(nb$Site) %in% c("SCORFF","AULNE")){
     nb <- nb %>% 
      mutate(Start = Start+200000,
             End = End+200000) %>% 
      dplyr::filter(Sample != 21)
     
  }else if (unique(nb$Site) == "BER"){
    nb <- nb %>% 
      mutate(Letter_new = case_when(Letter == "B"~"D",
                                    Letter == "C"~"B",
                                    Letter == "D"~"C",
                                    TRUE ~ Letter),
             Letter = Letter_new) %>% 
      dplyr::select(-Letter_new)
      
    
  }else if(unique(nb$Site) == "VIE"){
        nb <- nb %>% 
      mutate(Letter_new = case_when(Letter == "A"~"C",
                                    Letter %in% c("B","C") ~"A",
                                    Letter %in% c("D","E")~"B",
                                    TRUE ~ Letter),
             Letter = Letter_new) %>% 
      dplyr::select(-Letter_new)
    
  }else if(unique(nb$Site) == "VAN"){
    
    # No need to change the letters, it's already the righ ones in the notebook
    
  }
  
  for(ii in 1:nrow(nb)){
  
    a <- df_long %>% 
      dplyr::filter(dataset_Name == unique(nb$Site),
                    Spectra %in% c(nb$Start[ii]:nb$End[ii])) %>% 
      mutate(Sample = nb$Sample[ii],
             Letter = nb$Letter[ii],
             Obs = nb$Obs[ii])
    
    if(ii == 1){
      output <- a
    }  else{
      output <- output %>% 
        rbind(a)
    }
  
  }

  write.csv(output, paste0("Data/CSV/RAW_",unique(nb$Site),"_Spectra.csv"))
  
}

```

```{r loop plotting across CSV}


CSV_sites <- list.files("./Data/CSV", full.names = T) %>% 
  as.data.frame() %>% 
  rename(path = ".") %>% 
  mutate(name = gsub(".*/","",path) %>% gsub(".csv","",.)) %>% 
  filter(!name %in% c("all_spectra"))

for(i in 1:nrow(CSV_sites)){
  
  print(paste0(i,"/",nrow(CSV_sites)))
  
  df <- read.csv(CSV_sites$path[i]) %>% 
    select(-X) %>% 
  dplyr::filter(Wavelength >= 400,
                Wavelength <= 950,
                Letter %in% c("A","B","C","Field"))
  
  for(ii in 1:length(unique(df$Sample))){
    
    a <- df %>% 
      dplyr::filter(Sample == unique(df$Sample)[ii])
    
    plt <- ggplot(a)+
      geom_line(aes(x = Wavelength, y=ref, group = Name, color = as.factor(Letter)))+
      geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.1, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c("grey40" ,"yellow4","red"),
                       breaks = c("A",
                                  "B",
                                  "C"), 
                       labels = c("A -  Sparse on Table", "B - Sparse on Sediment" ,"C - High density"))+
      labs(color = " ")+
      theme_Bede()
    
    ggsave(paste0("Plot/", unique(a$dataset_Name),"/Sample_",unique(df$Sample)[ii],".png"), plt)
    
  }
}

```

```{r loop STD across CSV}

CSV_sites <- list.files("./Data/CSV", full.names = T) %>% 
  as.data.frame() %>% 
  rename(path = ".") %>% 
  mutate(name = gsub(".*/","",path) %>% gsub(".csv","",.)) %>% 
  filter(!name %in% c("Etel","ASD_Etel_October2023","all_spectra"))


for(i in 1:nrow(CSV_sites)){
  
  site = CSV_sites$name[i] %>% 
    gsub("RAW_","",.) %>% 
    gsub("_Spectra","",.)
  print(i)
  
  if(!file.exists(paste0("Output/",site,"_STD.csv"))){
     
  
    df <- read.csv(CSV_sites$path[i]) %>% 
      select(-X) %>% 
    dplyr::filter(Wavelength >= 400,
                  Wavelength <= 900) %>% 
    group_by(Name) %>% 
    reframe(STD = (ref - min(ref))/(max(ref)-min(ref)),
            Wavelength = Wavelength,
            ref = ref,
            Spectra = Spectra,
            dataset_Name = dataset_Name,
            Sample = Sample,
            Letter = Letter,
            Obs = Obs) 
    
    df_STD <- df %>% 
    group_by(Wavelength, Sample, Letter) %>%
    reframe(mean_STD = mean(STD),
            mean_RAW = mean(ref),
            dataset_Name = unique(dataset_Name)) %>% 
      mutate(ID = paste(dataset_Name,Sample,Letter, sep = "_"))
    
    write_csv(df_STD, paste0("Output/",unique(df_STD$dataset_Name),"_STD.csv"))
    
    rm(df)
    rm(df_STD) 
    
  }
  
}



```

```{r Process AV}

notebooks <- list.files("./Data/Notebook", full.names = T) %>% 
  as.data.frame() %>% 
  rename(path = ".") %>% 
  mutate(name = gsub(".*/","",path),
         site = gsub(".*_","",name) %>% gsub(".txt","",.))


df_without_notebooks <- df_long %>% 
  filter(!dataset_Name %in% notebooks$site)

unique(df_without_notebooks$dataset_Name)


df_AV <- df_without_notebooks %>% 
  filter(dataset_Name == "AV",
         !Name == "AV0100011") 


for (i in 1:22) {
  
  if (i == 1) {
    start = 0
    end = 9
  }else{
    start = start +10
    end = end + 10
  }
  
  names_i <- unique(df_AV$Name)[c(start:end)]
  
  a <- df_AV %>% 
    dplyr::filter(Name %in% names_i) %>% 
  dplyr::filter(Wavelength >= 400,
                Wavelength <= 900) %>% 
    group_by(Wavelength) %>% 
    reframe(mean_RAW = mean(ref),
            dataset_Name = unique(dataset_Name)) %>% 
    mutate(mean_STD = (mean_RAW - min(mean_RAW))/(max(mean_RAW)-min(mean_RAW)),
           Sample = i,
           Letter = "Field", 
           ID = paste(dataset_Name,Sample,Letter, sep = "_")) %>% 
    relocate(Wavelength,Sample,Letter,mean_STD,mean_RAW,dataset_Name,ID)
  
  if (i == 1) {
    output = a
    
  }else{
    output = rbind(output,a)
  }
}

 write_csv(output, paste0("Output/AV_STD.csv"))

```

```{r Process Etel}

df_ETE <- read.csv("Data/CSV/Etel/RAW_ASD_Etel_October2023.csv") %>% 
  dplyr::select(-X) %>%
  mutate(group = case_when(str_detect(spectra_name, "GRA01") ~ "GRA01",
                           str_detect(spectra_name, "GRA02") ~ "GRA02",
                           str_detect(spectra_name, "GRA03") ~ "GRA03",
                           str_detect(spectra_name, "LOR") ~ "LOR",
                           TRUE ~ "NA"),
         number = stringi::stri_replace_all_regex(spectra_name,group,"") %>% as.numeric(),
         Letter = "Field",
         Sample = case_when(group == "GRA01" & number >= 50 & number < 100 ~ 1,
                        group == "GRA01" & number >= 100 & number < 150 ~ 2,
                        group == "GRA01" & number >= 150 & number < 200 ~ 3,
                        group == "GRA02" ~ 4,
                        group == "GRA03" ~ 5,
                        group == "LOR" & number >= 50 & number < 100 ~ 6,
                        group == "LOR" & number >= 100 & number < 150 ~ 7,
                        group == "LOR" & number >= 150 & number < 200 ~ 8,
                        group == "LOR" & number >= 200 & number < 250 ~ 9,
                        TRUE ~ NA),
         dataset_Name = "ETEL",
         ID = paste(dataset_Name, Sample,Letter, sep = "_")) %>% 
  filter(!is.na(Sample),
         Wavelength %in% c(400:900)) %>% 
  group_by(Wavelength,ID) %>% 
  reframe(mean_RAW = mean(Reflectance),
          Sample = unique(Sample),
          Letter = unique(Letter),
          dataset_Name = unique(dataset_Name)) %>% 
  ungroup() %>% 
  group_by(ID) %>% 
  mutate(mean_STD = (mean_RAW-min(mean_RAW))/(max(mean_RAW)-min(mean_RAW))) %>% 
  relocate(Wavelength, Sample, Letter, mean_STD, mean_RAW, dataset_Name,ID)

ggplot(df_ETE) +
  geom_line(aes(x = Wavelength, y = mean_STD, color = ID))

write_csv(df_ETE, paste0("Output/",unique(df_ETE$dataset_Name),"_STD.csv"))

```

```{r plot check}

"Output/VIE_STD.csv" %>% 
  read.csv() %>% 
  ggplot()+
  geom_line(aes(x = Wavelength, y = mean_STD, color = ID), show.legend = F)

```

```{r BER}


#### NO NEED TO RUN THIS IF THE CHUNK loop across notebooks HAS ALREADY BEEN RUN 

df_Ber_long <- df %>% 
  pivot_longer(-Wavelength, names_to = "Name",values_to = "ref") %>% 
  mutate(Name = gsub(".asd","",Name),
         Spectra = as.numeric(gsub("\\D", "", Name)),
         dataset_Name = gsub("[[:digit:]]","",Name) %>% 
           gsub("-","",.)) %>% 
  dplyr::filter(str_detect(dataset_Name, "BER"),
                Wavelength >= 400,
                Wavelength <= 950) 


Notebook_BER <- read.delim("Data/Notebook/Sampling_Notebook_BER.txt")


for(i in 1:nrow(Notebook_BER)){
  
  a <- df_Ber_long %>% 
    dplyr::filter(Spectra %in% c(Notebook_BER$Start[i]:Notebook_BER$End[i])) %>% 
    mutate(Sample = Notebook_BER$Sample[i],
           Letter = Notebook_BER$Letter[i],
           Obs = Notebook_BER$Obs[i])
  
  if(i == 1){
    output_BER <- a
  }  else{
    output_BER <- output_BER %>% 
      rbind(a)
  }
  
}

write.csv(output_BER, "Data/CSV/RAW_BER_Spectra.csv")

for(i in 1:length(unique(output_BER$Sample))){
  
  sp <- output_BER %>% 
   dplyr::filter(Sample == unique(output_BER$Sample)[i]) %>% 
    mutate(Letter = case_when(Letter == "A" ~ "Sparse on table",
                              Letter == "B" ~ "Bare Sediment",
                              Letter == "C" ~ "Sparse on Sediment",
                              Letter == "D" ~ "High density"))
  
  plot <- ggplot(sp)+
    geom_line(aes(x = Wavelength, y = ref, color = Letter, group = Name))+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.1, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.13, label = paste0("Specie: ", unique(Obs))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c("brown", "red","orange", "grey60"))+
    xlab("Wv (nm)")+
    ylab("Reflectance")+
    theme_Bede()+
    theme(axis.text.x = element_text(size = 15),
          axis.text.y = element_text(size = 15),
          legend.position = "top", 
          legend.key.width = unit(1,"cm"),
          legend.key.height = unit(3,"mm"))
  
  ggsave(paste0("Plot/BER/RAW/Sample",unique(sp$Sample),".jpg" ), plot, width = 10, height = 10, dpi = 200)

}


####  STD 

df_BER_STD <- output_BER %>% 
  dplyr::filter(Wavelength >= 400,
                Wavelength <= 950) %>% 
  group_by(Name) %>% 
  reframe(STD = (ref - min(ref))/(max(ref)-min(ref)),
          Wavelength = Wavelength,
          ref = ref,
          Spectra = Spectra,
          dataset_Name = dataset_Name,
          Sample = Sample,
          Letter = Letter,
          Obs = Obs)


for(i in 1:length(unique(df_BER_STD$Sample))){
  
  sp_STD <- df_BER_STD %>% 
   dplyr::filter(Sample == unique(output_BER$Sample)[i]) %>% 
    mutate(Letter = case_when(Letter == "A" ~ "Sparse on table",
                              Letter == "B" ~ "Bare Sediment",
                              Letter == "C" ~ "Sparse on Sediment",
                              Letter == "D" ~ "High density"))
  
  plot <- ggplot(sp_STD)+
    geom_line(aes(x = Wavelength, y = STD, color = Letter, group = Name))+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.1, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.13, label = paste0("Specie: ", unique(Obs))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c("brown", "red","orange", "grey60"))+
    xlab("Wv (nm)")+
    ylab("STD Reflectance")+
    theme_Bede()+
    theme(axis.text.x = element_text(size = 15),
          axis.text.y = element_text(size = 15),
          legend.position = "top", 
          legend.key.width = unit(1,"cm"),
          legend.key.height = unit(3,"mm"))
  
  ggsave(paste0("Plot/BER/STD/Sample",unique(sp_STD$Sample),"_STD.jpg" ), plot, width = 10, height = 10, dpi = 200)

}


```

```{r VIE}

#### NO NEED TO RUN THIS IF THE CHUNK loop across notebooks HAS ALREADY BEEN RUN 


df_VIE_long<- df_long %>% 
  dplyr::filter(dataset_Name == "GRA-VIE",
                Wavelength >= 400,
                Wavelength <= 950)

Notebook_VIE <- read.delim("Data/Notebook/Sampling_Notebook_VIE.txt")

for(i in 1:nrow(Notebook_VIE)){
  
  a <- df_VIE_long %>% 
    dplyr::filter(Spectra %in% c(Notebook_VIE$Start[i]:Notebook_VIE$End[i])) %>% 
    mutate(Sample = Notebook_VIE$Sample[i],
           Letter = Notebook_VIE$Letter[i],
           Obs = Notebook_VIE$Obs[i])
  
  if(i == 1){
    output_VIE <- a
  }  else{
    output_VIE <- output_VIE %>% 
      rbind(a)
  }
  
}


write.csv(output_VIE, "Data/CSV/RAW_VIE_Spectra.csv")

for(i in 1:length(unique(output_VIE$Sample))){
  
  sp <- output_VIE %>% 
   dplyr::filter(Sample == unique(output_VIE$Sample)[i]) 
    # mutate(Letter = case_when(Letter == "A" ~ "High density",
    #                           # Letter == "B" ~ "Bare Sediment",
    #                           Letter == "B" ~ "Sparse on table",
    #                           Letter == "C" ~ "Sparse on Sediment",
    #                           Letter == "D" ~ "NA",
    #                           Letter == "E" ~ "Sediment"))
  
  
  
  
  plot <- ggplot(sp)+
    geom_line(aes(x = Wavelength, y = ref, color = as.factor(Letter), group = Name))+
    geom_text(aes(x = 850, y = 0.68, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    geom_text(aes(x = 850, y = 0.65, label = paste0("Specie: ", unique(Obs))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c( "red","orange","orange3","yellow3","yellow4","brown", "grey30","grey40","grey50" ),
                       breaks = c("A",
                                  "B",
                                  "C",
                                  "D",
                                  "E",
                                  "F",
                                  "G",
                                  "H",
                                  "I"), 
                       labels = c("High density","Sparse on table1","Sparse on table2","Sparse on Sediment1","Sparse on Sediment2","Sediment", "Fucus1", "Fucus2", "Fucus3"))+
    xlab("Wv (nm)")+
    ylab("Reflectance")+
    ylim(c(0,0.7))+
    theme_Bede()+
    labs(color = " ")+
    theme(axis.text.x = element_text(size = 15),
          axis.text.y = element_text(size = 15),
          legend.position = "top", 
          legend.key.width = unit(1,"cm"),
          legend.key.height = unit(3,"mm"))
  
  if(file.exists(paste0("Data/Pictures/VIE/Lab/VIE",unique(sp$Sample),".jpg"))){
    img<-rast(paste0("Data/Pictures/VIE/Lab/VIE",unique(sp$Sample),".jpg"))
    
    
    img_plot<-ggplot()+
      geom_spatraster_rgb(data = img)+
      coord_equal()+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      theme_void()
    
    plot <- plot +
      annotation_custom(ggplotGrob(img_plot), xmin = 400, xmax = 670, ymin = 0.4, ymax = 0.72)
    
  }else{
    if(unique(sp$Obs == "Fucus sp.")){
     img<-rast("Data/Pictures/VIE/Lab/fucus.jpg")
    
    
    img_plot<-ggplot()+
      geom_spatraster_rgb(data = img)+
      coord_equal()+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      theme_void()
    
    plot <- plot +
      annotation_custom(ggplotGrob(img_plot), xmin = 400, xmax = 670, ymin = 0.4, ymax = 0.72) 
    }
      
    
    }
  
  ggsave(paste0("Plot/VIE/RAW/Sample",unique(sp$Sample),".jpg" ), plot, width = 10, height = 10, dpi = 200)

}



####  STD 

df_VIE_STD <- output_VIE %>% 
  dplyr::filter(Wavelength >= 400,
                Wavelength <= 950) %>% 
  group_by(Name) %>% 
  reframe(STD = (ref - min(ref))/(max(ref)-min(ref)),
          Wavelength = Wavelength,
          ref = ref,
          Spectra = Spectra,
          dataset_Name = dataset_Name,
          Sample = Sample,
          Letter = Letter,
          Obs = Obs)


for(i in 1:length(unique(df_VIE_STD$Sample))){
  
  sp_STD <- df_VIE_STD %>% 
   dplyr::filter(Sample == unique(output_VIE$Sample)[i])
  
  plot <- ggplot(sp_STD)+
    geom_line(aes(x = Wavelength, y = STD, color = Letter, group = Name))+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.1, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.13, label = paste0("Specie: ", unique(Obs))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c( "red","orange","orange3","yellow3","yellow4","brown", "grey30","grey40","grey50" ),
                       breaks = c("A","B","C","D","E","F","G","H","I"), 
                       labels = c("High density","Sparse on table1","Sparse on table2","Sparse on Sediment1","Sparse on Sediment2","Sediment", "Fucus1", "Fucus2", "Fucus3"))+
    xlab("Wv (nm)")+
    ylab("STD Reflectance")+
    theme_Bede()+
    theme(axis.text.x = element_text(size = 15),
          axis.text.y = element_text(size = 15),
          legend.position = "top", 
          legend.key.width = unit(1,"cm"),
          legend.key.height = unit(3,"mm"))
  
  ggsave(paste0("Plot/VIE/STD/Sample",unique(sp_STD$Sample),"_STD.jpg" ), plot, width = 10, height = 10, dpi = 200)

}


```

```{r VANNE}

#### NO NEED TO RUN THIS IF THE CHUNK loop across notebooks HAS ALREADY BEEN RUN 

df_VAN_long<- df_long %>% 
  dplyr::filter(dataset_Name == "GRA-VAN",
                Wavelength >= 400,
                Wavelength <= 950)


Notebook_VAN <- read.delim("Data/Notebook/Sampling_Notebook_VAN.txt")

for(i in 1:nrow(Notebook_VAN)){
  
  a <- df_VAN_long %>% 
    dplyr::filter(Spectra %in% c(Notebook_VAN$Start[i]:Notebook_VAN$End[i])) %>% 
    mutate(Sample = Notebook_VAN$Sample[i],
           Letter = Notebook_VAN$Letter[i],
           Obs = as.character(Notebook_VAN$Obs[i]))
  
  if(i == 1){
    output_VAN <- a
  }  else{
    output_VAN <- output_VAN %>% 
      rbind(a)
  }
  
}

output_VAN <- output_VAN %>% 
  dplyr::filter(Name != "GRA-VAN00810")

write.csv(output_VAN, "Data/CSV/RAW_VAN_Spectra.csv")

for(i in 1:length(unique(output_VAN$Sample))){
  
  sp <- output_VAN %>% 
   dplyr::filter(Sample == unique(output_VAN$Sample)[i]) 
    # mutate(Letter = case_when(Letter == "A" ~ "High density",
    #                           # Letter == "B" ~ "Bare Sediment",
    #                           Letter == "B" ~ "Sparse on table",
    #                           Letter == "C" ~ "Sparse on Sediment",
    #                           Letter == "D" ~ "NA",
    #                           Letter == "E" ~ "Sediment"))
  
  
  unique(sp$Name)
  
  plot <- ggplot(sp)+
    geom_line(aes(x = Wavelength, y = ref, color = as.factor(Letter), group = Name))+
    geom_text(aes(x = 850, y = 0.68, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    geom_text(aes(x = 850, y = 0.65, label = paste0("Specie: ", unique(Obs))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c("grey30","orange","red", "green4", "red1", "red4"),
                       breaks = c("A","B","C","D","E","F"), 
                       labels = c("Sparse on Table","Sparse on Sediment","High density", "Green algae", "Red Algae1", "Red Algae2"))+
    xlab("Wv (nm)")+
    ylab("Reflectance")+
    ylim(c(0,0.7))+
    theme_Bede()+
    labs(color = " ")+
    theme(axis.text.x = element_text(size = 15),
          axis.text.y = element_text(size = 15),
          legend.position = "top", 
          legend.key.width = unit(1,"cm"),
          legend.key.height = unit(3,"mm"))
  
  if(file.exists(paste0("Data/Pictures/VAN/Lab/VAN",unique(sp$Sample),".jpg"))){
    img<-rast(paste0("Data/Pictures/VAN/Lab/VAN",unique(sp$Sample),".jpg"))
    
    
    img_plot<-ggplot()+
      geom_spatraster_rgb(data = img)+
      coord_equal()+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      theme_void()
    
    plot <- plot +
      annotation_custom(ggplotGrob(img_plot), xmin = 400, xmax = 670, ymin = 0.4, ymax = 0.72)
    
  }else{
    if(unique(sp$Obs == "Green and Red Algae")){
     img<-rast("Data/Pictures/VAN/Lab/Green_and_Red.jpg")
    
    
    img_plot<-ggplot()+
      geom_spatraster_rgb(data = img)+
      coord_equal()+
      scale_x_continuous(expand = c(0,0))+
      scale_y_continuous(expand = c(0,0))+
      theme_void()
    
    plot <- plot +
      annotation_custom(ggplotGrob(img_plot), xmin = 400, xmax = 670, ymin = 0.4, ymax = 0.72) 
    }
      
    
    }
  
  ggsave(paste0("Plot/VAN/RAW/Sample",unique(sp$Sample),".jpg" ), plot, width = 10, height = 10, dpi = 200)

}




####  STD 

df_VAN_STD <- output_VAN %>% 
  dplyr::filter(Wavelength >= 400,
                Wavelength <= 950) %>% 
  group_by(Name) %>% 
  reframe(STD = (ref - min(ref))/(max(ref)-min(ref)),
          Wavelength = Wavelength,
          ref = ref,
          Spectra = Spectra,
          dataset_Name = dataset_Name,
          Sample = Sample,
          Letter = Letter,
          Obs = Obs)


for(i in 1:length(unique(df_VAN_STD$Sample))){
  
  sp_STD <- df_VAN_STD %>% 
   dplyr::filter(Sample == unique(output_VAN$Sample)[i])
  
  plot <- ggplot(sp_STD)+
    geom_line(aes(x = Wavelength, y = STD, color = Letter, group = Name))+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.1, label = paste0("Sample: ", unique(Sample))),
              size = 5, hjust = 0)+
    geom_text(aes(x = 400, y = max(ref)-(max(ref)-min(ref))*0.13, label = paste0("Specie: ", unique(Obs))),
              size = 5, hjust = 0)+
    scale_color_manual(values = c("grey30","orange","red", "green4", "red1", "red4"),
                       breaks = c("A","B","C","D","E","F"), 
                       labels = c("Sparse on Table","Sparse on Sediment","High density", "Green algae", "Red Algae1", "Red Algae2"))+
    xlab("Wv (nm)")+
    ylab("STD Reflectance")+
    theme_Bede()+
    theme(axis.text.x = element_text(size = 15),
          axis.text.y = element_text(size = 15),
          legend.position = "top", 
          legend.key.width = unit(1,"cm"),
          legend.key.height = unit(3,"mm"))
  
  ggsave(paste0("Plot/VAN/STD/Sample",unique(sp_STD$Sample),"_STD.jpg" ), plot, width = 10, height = 10, dpi = 200)

}



```

```{r SAJA}

Saja_df_field <- read.csv("D:/Git_repo/InvaSea/Data/Spain/Gracilaria-Saja-reflectance.txt", sep="") %>% 
  pivot_longer(-wl, names_to = "Spectra", values_to = "Value") %>% 
  group_by(Spectra) %>% 
  mutate(std = (Value-min(Value))/(max(Value)-min(Value))) %>% 
  ungroup() %>% 
  rename(Wavelength = "wl",
         mean_STD = "std",
         mean_RAW = Value) %>% 
  mutate(Sample = gsub("[^0-9]", "", Spectra) %>% as.numeric(),
         Letter = "Field", 
         dataset_Name = "SAJA",
         ID = paste0(dataset_Name,"_",Sample,"_",Letter)) %>% 
  dplyr::select(-Spectra) %>% 
  dplyr::select(Wavelength,Sample,Letter,mean_STD,mean_RAW,dataset_Name,ID)

Saja_df_lab <- read.csv("D:/Git_repo/InvaSea/Data/Spain/SAJA-reflectance.txt", sep="") %>% 
  pivot_longer(-Wavelength, names_to = "Spectra", values_to = "Value") %>%
  dplyr::filter(Wavelength >= 400 & Wavelength <= 900) %>% 
  # dplyr::filter(Sample >=111) %>% 
  mutate(Sample = gsub("[^0-9]", "", Spectra) %>% as.numeric(),
         dataset_Name = "SAJA",
         Sample1 = case_when(
                             # Sample < 90 ~ NA,
                             Sample >=90 &  Sample < 120 ~ 8,
                             Sample >=120 &  Sample < 150 ~ 10,
                             Sample >=150 &  Sample < 180 ~ 9,
                             Sample >=180 &  Sample < 210 ~ 4,
                             Sample >=210 &  Sample < 240 ~ 2,
                             Sample >=240 &  Sample < 270 ~ 5,
                             Sample >=270 &  Sample < 300 ~ 7,
                             Sample >=300 &  Sample < 330 ~ 3,
                             Sample >=330 &  Sample < 360 ~ 1,
                             Sample >=360 &  Sample < 390 ~ 6,
                             Sample >=390 &  Sample < 420 ~ 11,
                             Sample >=420 &  Sample < 450 ~ 12,
                             Sample >=450 &  Sample < 480 ~ 13,
                             Sample >=480 &  Sample < 510 ~ 14,
                             Sample >=510 &  Sample < 540 ~ 15,
                             Sample >=540 &  Sample < 570 ~ 16,
                             Sample >=570 &  Sample < 600 ~ 17,
                             Sample >=600 &  Sample < 630 ~ 18,
                             Sample >=630 &  Sample < 660 ~ 19,
                             Sample >=660 &  Sample < 690 ~ 20,
                             Sample >=690 &  Sample < 720 ~ 21,
                             T ~ NA),
         Letter = case_when(Sample > 89 & Sample <= 99 ~ "A",
                            Sample > 99 & Sample <= 109 ~ "B",
                            Sample > 109 & Sample <= 119 ~ "C",
                            Sample > 119 & Sample <= 129 ~ "A",
                            Sample > 129 & Sample <= 139 ~ "B",
                            Sample > 139 & Sample <= 149 ~ "C",
                            Sample > 149 & Sample <= 159 ~ "A",
                            Sample > 159 & Sample <= 169 ~ "B",
                            Sample > 169 & Sample <= 179 ~ "C",
                            Sample > 179 & Sample <= 189 ~ "A",
                            Sample > 189 & Sample <= 199 ~ "B",
                            Sample > 199 & Sample <= 209 ~ "C",
                            Sample > 209 & Sample <= 219 ~ "A",
                            Sample > 219 & Sample <= 229 ~ "B",
                            Sample > 229 & Sample <= 239 ~ "C",
                            Sample > 239 & Sample <= 249 ~ "A",
                            Sample > 249 & Sample <= 259 ~ "B",
                            Sample > 259 & Sample <= 269 ~ "C",
                            Sample > 269 & Sample <= 279 ~ "A",
                            Sample > 279 & Sample <= 289 ~ "B",
                            Sample > 289 & Sample <= 299 ~ "C",
                            Sample > 299 & Sample <= 309 ~ "A",
                            Sample > 309 & Sample <= 319 ~ "B",
                            Sample > 319 & Sample <= 329 ~ "C",
                            Sample > 329 & Sample <= 339 ~ "A",
                            Sample > 339 & Sample <= 349 ~ "B",
                            Sample > 349 & Sample <= 359 ~ "C",
                            Sample > 359 & Sample <= 369 ~ "A",
                            Sample > 369 & Sample <= 379 ~ "B",
                            Sample > 379 & Sample <= 389 ~ "C",
                            Sample > 389 & Sample <= 399 ~ "A",
                            Sample > 399 & Sample <= 409 ~ "B",
                            Sample > 409 & Sample <= 419 ~ "C",
                            Sample > 419 & Sample <= 429 ~ "A",
                            Sample > 429 & Sample <= 439 ~ "B",
                            Sample > 439 & Sample <= 449 ~ "C",
                            Sample > 449 & Sample <= 459 ~ "A",
                            Sample > 459 & Sample <= 469 ~ "B",
                            Sample > 469 & Sample <= 479 ~ "C",
                            Sample > 479 & Sample <= 489 ~ "A",
                            Sample > 489 & Sample <= 499 ~ "B",
                            Sample > 499 & Sample <= 509 ~ "C",
                            Sample > 509 & Sample <= 519 ~ "A",
                            Sample > 519 & Sample <= 529 ~ "B",
                            Sample > 529 & Sample <= 539 ~ "C",
                            Sample > 539 & Sample <= 549 ~ "A",
                            Sample > 549 & Sample <= 559 ~ "B",
                            Sample > 559 & Sample <= 569 ~ "C",
                            Sample > 569 & Sample <= 579 ~ "A",
                            Sample > 579 & Sample <= 589 ~ "B",
                            Sample > 589 & Sample <= 599 ~ "C",
                            Sample > 599 & Sample <= 609 ~ "A",
                            Sample > 609 & Sample <= 619 ~ "B",
                            Sample > 619 & Sample <= 629 ~ "C",
                            Sample > 629 & Sample <= 639 ~ "A",
                            Sample > 639 & Sample <= 649 ~ "B",
                            Sample > 649 & Sample <= 659 ~ "C",
                            Sample > 659 & Sample <= 669 ~ "A",
                            Sample > 669 & Sample <= 679 ~ "B",
                            Sample > 679 & Sample <= 689 ~ "C",
                            Sample > 689 & Sample <= 699 ~ "A",
                            Sample > 699 & Sample <= 709 ~ "B",
                            Sample > 709 & Sample <= 719 ~ "C",
                            TRUE ~ "Coucou"),
         ID = paste0(dataset_Name,"_",Sample1,"_",Letter)) %>% 
  dplyr::filter(!is.na(Sample1)) %>% 
  group_by(Wavelength,ID) %>% 
  reframe(mean_RAW = mean(Value),
          Sample = unique(Sample1),
          dataset_Name = unique(dataset_Name),
          Letter = unique(Letter)) %>% 
  ungroup() %>% 
  group_by(ID) %>% 
  mutate(mean_STD = (mean_RAW-min(mean_RAW))/(max(mean_RAW)-min(mean_RAW))) %>% 
  dplyr::select(Wavelength,Sample,Letter,mean_STD,mean_RAW,dataset_Name,ID)


saja_df <- Saja_df_field %>% 
  bind_rows(Saja_df_lab)

write_csv(Saja_df, paste0("Output/",unique(Saja_df$dataset_Name),"_STD.csv"))


```

```{r Vigo}

### FIELD #####

Vigo_df <- read.csv("D:/Git_repo/InvaSea/Data/Spain/20240626-GR_Vigo.txt", sep="")%>% 
  pivot_longer(-Wavelength, names_to = "Spectra", values_to = "Rad") %>% 
  mutate(Spectra = gsub(".asd","",Spectra))

ggplot(Vigo_df)+
  geom_line(aes(x = Wavelength, y = Rad, group = Spectra))

AUC <- Vigo_df %>%
  group_by(Spectra) %>% 
  dplyr::summarise(
    AUC = DescTools::AUC(Wavelength,Rad)
  )

Vigo_df<-Vigo_df %>% 
  left_join(AUC, by = "Spectra") %>% 
  mutate(type = case_when(AUC > 35 ~ "Spectralon",
                          TRUE ~ "Spectra"))

for(i in 1:nrow(Vigo_df)){
  if(i == 1){
    lot = 1
  }else{
    if(Vigo_df$type[i-1]!=Vigo_df$type[i]){
      lot = lot+1
    }
  }
  Vigo_df$lot[i] = lot
}

Vigo_df <- Vigo_df %>%
  arrange(Spectra) %>% 
  mutate(lot = cumsum(type != lag(type, default = first(type))))

spectralon_avg<-Vigo_df %>% 
  filter(type == "Spectralon") %>% 
  group_by(lot,Wavelength) %>% 
  reframe(Radiance = mean(Rad)) 

df_Vigo_Field<-Vigo_df %>% 
  filter(!type == "Spectralon") %>% 
  group_by(lot,Wavelength) %>% 
  reframe(Rad = mean(Rad)) %>%
  mutate(lot_minus1 = lot - 1) %>%
  left_join(spectralon_avg, 
            by = c("lot_minus1" = "lot", "Wavelength" = "Wavelength")) %>%
  mutate(Reflectance = Rad / Radiance) %>%
  select(-Rad, -Radiance, -lot_minus1) %>% 
  dplyr::filter(Wavelength >= 400 & Wavelength <=900)  %>% 
  rename(Sample = lot) %>% 
  group_by(Sample) %>% 
  mutate(std = (Reflectance-min(Reflectance))/(max(Reflectance)-min(Reflectance))) %>%  
  ungroup() %>% 
  mutate(Letter = "Field", 
         dataset_Name = "VIGO",
         ID = paste0(dataset_Name,"_",Sample,"_",Letter)) %>% 
  rename(mean_RAW = "Reflectance",
         mean_STD = std) %>% 
  dplyr::select(Wavelength,Sample,Letter,mean_STD,mean_RAW,dataset_Name,ID)
  
# 
# ggplot(df_spectra)+
#   geom_line(aes(x = Wavelength, y = mean_STD, group = ID,color = Sample))

###############

Vigo_df_lab <- read.csv("D:/Git_repo/InvaSea/Data/Spain/CESANTES-reflectance.txt", sep="") %>% 
  pivot_longer(-Wavelength, names_to = "Spectra", values_to = "Value") %>%
  dplyr::filter(Wavelength >= 400 & Wavelength <= 900) %>% 
  rename(mean_RAW = Value) %>% 
  mutate(Sample = gsub("[^0-9]", "", Spectra) %>% as.numeric(),
         Sample1 = case_when(Sample <= 29 ~ 1,
                            Sample > 29 & Sample <= 59 ~ 2,
                            Sample > 59 & Sample <= 89 ~ 3,
                            Sample > 89 & Sample <= 119 ~ 4,
                            Sample > 119 & Sample <= 149 ~ 5,
                            Sample > 149 & Sample <= 179 ~ 6,
                            Sample > 179 & Sample <= 209 ~ 7,
                            Sample > 209 & Sample <= 239 ~ 8,
                            Sample > 239 & Sample <= 269 ~ 9,
                            Sample > 269 & Sample <= 299 ~ 10,
                            Sample > 299 & Sample <= 329 ~ 11,
                            Sample > 329 & Sample <= 359 ~ 12,
                            Sample > 359 & Sample <= 389 ~ 13,
                            Sample > 389 & Sample <= 419 ~ 14,
                            Sample > 419 & Sample <= 449 ~ 15,
                            Sample > 449 & Sample <= 479 ~ 16,
                            Sample > 479 & Sample <= 509 ~ 17,
                            Sample > 509 & Sample <= 539 ~ 18,
                            Sample > 539 & Sample <= 569 ~ 19,
                            Sample > 569 & Sample <= 609 ~ 20,
                            T ~ Sample
                            ),
         Letter = case_when(Sample <= 9 ~ "A",
                            Sample > 9 & Sample <= 19 ~ "B",
                            Sample > 19 & Sample <= 29 ~ "C",
                            Sample > 29 & Sample <= 39 ~ "A",
                            Sample > 39 & Sample <= 49 ~ "B",
                            Sample > 49 & Sample <= 59 ~ "C",
                            Sample > 59 & Sample <= 69 ~ "A",
                            Sample > 69 & Sample <= 79 ~ "B",
                            Sample > 79 & Sample <= 89 ~ "C",
                            Sample > 89 & Sample <= 99 ~ "A",
                            Sample > 99 & Sample <= 109 ~ "B",
                            Sample > 109 & Sample <= 119 ~ "C",
                            Sample > 119 & Sample <= 129 ~ "A",
                            Sample > 129 & Sample <= 139 ~ "B",
                            Sample > 139 & Sample <= 149 ~ "C",
                            Sample > 149 & Sample <= 159 ~ "A",
                            Sample > 159 & Sample <= 169 ~ "B",
                            Sample > 169 & Sample <= 179 ~ "C",
                            Sample > 179 & Sample <= 189 ~ "A",
                            Sample > 189 & Sample <= 199 ~ "B",
                            Sample > 199 & Sample <= 209 ~ "C",
                            Sample > 209 & Sample <= 219 ~ "A",
                            Sample > 219 & Sample <= 229 ~ "B",
                            Sample > 229 & Sample <= 239 ~ "C",
                            Sample > 239 & Sample <= 249 ~ "A",
                            Sample > 249 & Sample <= 259 ~ "B",
                            Sample > 259 & Sample <= 269 ~ "C",
                            Sample > 269 & Sample <= 279 ~ "A",
                            Sample > 279 & Sample <= 289 ~ "B",
                            Sample > 289 & Sample <= 299 ~ "C",
                            Sample > 299 & Sample <= 309 ~ "A",
                            Sample > 309 & Sample <= 319 ~ "B",
                            Sample > 319 & Sample <= 329 ~ "C",
                            Sample > 329 & Sample <= 339 ~ "A",
                            Sample > 339 & Sample <= 349 ~ "B",
                            Sample > 349 & Sample <= 359 ~ "C",
                            Sample > 359 & Sample <= 369 ~ "A",
                            Sample > 369 & Sample <= 379 ~ "B",
                            Sample > 379 & Sample <= 389 ~ "C",
                            Sample > 389 & Sample <= 399 ~ "A",
                            Sample > 399 & Sample <= 409 ~ "B",
                            Sample > 409 & Sample <= 419 ~ "C",
                            Sample > 419 & Sample <= 429 ~ "A",
                            Sample > 429 & Sample <= 439 ~ "B",
                            Sample > 439 & Sample <= 449 ~ "C",
                            Sample > 449 & Sample <= 459 ~ "A",
                            Sample > 459 & Sample <= 469 ~ "B",
                            Sample > 469 & Sample <= 479 ~ "C",
                            Sample > 479 & Sample <= 489 ~ "A",
                            Sample > 489 & Sample <= 499 ~ "B",
                            Sample > 499 & Sample <= 509 ~ "C",
                            Sample > 509 & Sample <= 519 ~ "A",
                            Sample > 519 & Sample <= 529 ~ "B",
                            Sample > 529 & Sample <= 539 ~ "C",
                            Sample > 539 & Sample <= 549 ~ "A",
                            Sample > 549 & Sample <= 559 ~ "B",
                            Sample > 559 & Sample <= 569 ~ "C",
                            Sample > 569 & Sample <= 579 ~ "A",
                            Sample > 579 & Sample <= 589 ~ "B",
                            Sample > 589 & Sample <= 599 ~ "C"),
         dataset_Name = "VIGO",
         ID = paste0(dataset_Name,"_",Sample1,"_",Letter)) %>%
  group_by(ID,Wavelength) %>% 
  reframe(mean_RAW = mean(mean_RAW),
          Sample = Sample1,
          Letter = Letter,
          dataset_Name = dataset_Name) %>% 
  ungroup() %>% 
  group_by(ID) %>% 
  mutate(mean_STD = (mean_RAW-min(mean_RAW))/(max(mean_RAW)-min(mean_RAW))) %>% 
  ungroup() %>% 
  dplyr::select(Wavelength,Sample,Letter,mean_STD,mean_RAW,dataset_Name,ID) 


vigo_all <- df_Vigo_Field %>% 
  bind_rows(Vigo_df_lab)

write_csv(vigo_all, paste0("Output/",unique(vigo_all$dataset_Name),"_STD.csv"))
```



